version: '3.8'

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: optimum-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
      - mysql8-service
    networks:
      - nginx-php82-mysql8
  php82-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: optimum-php82
    ports:
      - "9001:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php82-mysql8
  mysql8-service:
    image: mysql:8
    container_name: optimum-mysql8
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - nginx-php82-mysql8

  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: optimum-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - nginx-php82-mysql8

networks:
  nginx-php82-mysql8:
